#ifndef UTILITY_H
#define UTILITY_H

#include "entities/base/Entity.h"
#include "entities/base/Subject.h"

#include <string>

/**
 * @class Utility
 * @brief Represents a utility entity in the city builder, such as power plants or sewage systems.
 *
 * The Utility class is a specialized entity that has an output value, such as electricity or water.
 */
class Utility : public Entity, public Subject
{
public:
    /**
     * @brief Constructs a Utility object with the specified parameters.
     * 
     * This constructor initializes a Utility instance with various attributes including output, 
     * resource consumption, effects, dimensions, and positioning.
     * 
     * @param output         The output value of the utility.
     * @param electricity    The amount of electricity consumed by the utility.
     * @param water          The amount of water consumed by the utility.
     * @param symbol         A string representing the utility's symbol.
     * @param radius         The radius of the utility's effect area.
     * @param localEffect    The local effect generated by the utility.
     * @param globalEffect   The global effect generated by the utility.
     * @param width          The width of the utility.
     * @param height         The height of the utility.
     * @param revenue        The revenue generated by the utility.
     * @param size           The size of the utility, represented as an enumerator (Size).
     * @param xPos           The x-coordinate position of the utility.
     * @param yPos           The y-coordinate position of the utility.
     * @param buildTime      The time required to build the utility.
     */
    Utility(int output, int electricity, int water, std::string symbol, int radius, int localEffect, int globalEffect, int width, int height, int revenue, Size size, int xPos, int yPos, int buildTime);

    /**
     * @brief Copy constructor for the Utility class.
     * 
     * Creates a deep copy of a Utility object by copying the attributes of an existing Utility object.
     * 
     * @param utility Pointer to the existing Utility object to be copied.
     */
    Utility(Utility* utility);

    /**
     * @brief Default constructor for the Utility class.
     * 
     * Creates a new Utility object without initializing any of it's values (naughty).
     */
    Utility();

    /**
     * @brief Destructor for the Utility object.
     */
    virtual ~Utility();

    /**
     * @brief Pure virtual function to update the utility's state.
     *
     * Implement this method to define how the utility behaves when its state is updated.
     */
    virtual void update() = 0;

    /**
     * @brief Retrieves the output of the utility.
     * 
     * @return The output value of the utility.
     */
    virtual int getOutput();

    /**
     * @brief Sets the output value of the utility.
     * 
     * @param output The new output value to be set.
     */
    void setOutput(int output);

    /**
     * @brief Pure virtual function to clone the utility.
     *
     * Implement this method to create a copy of the current utility instance.
     * 
     * @return A pointer to a new cloned Utility object.
     */
    virtual Entity* clone() = 0;

private:
    int output; ///< The output value of the utility (e.g., electricity or water produced).
};

#endif // UTILITY_H