#ifndef ENTITYCONFIG_H
#define ENTITYCONFIG_H

#include "Cost.h"
#include "EntityType.h" // Include EntityType
#include "Size.h"       // Include Size
#include <string>

/// @brief Configuration struct for an entity.
struct EntityConfig
{
  Cost cost;                    ///< Cost of the entity.
  int electricityConsumption;   ///< Electricity consumption level.
  int waterConsumption;         ///< Water consumption level.
  std::string symbol;           ///< Symbol representing the entity.
  int effectRadius;             ///< Radius of the entity's effect.
  int localEffectStrength;      ///< Strength of the local effect.
  int globalEffectStrength;     ///< Strength of the global effect.
  int width;                    ///< Width of the entity.
  int height;                   ///< Height of the entity.
  int revenue;                  ///< Revenue generated by the entity.
  int buildTime;                ///< Time required to build the entity.
  EntityType entityType;        ///< Type of the entity.
  Size size;                    ///< Size category of the entity.

  /// @brief Default constructor initializing default values.
  EntityConfig()
      : cost(), electricityConsumption(0), waterConsumption(0), symbol(""),
        effectRadius(0), localEffectStrength(0), globalEffectStrength(0),
        width(1), height(1), revenue(0), buildTime(0),
        entityType(EntityType::UNKNOWN), size(Size::SMALL) {}

  /// @brief Constructor initializing all properties.
  /// @param cost Cost of the entity.
  /// @param electricity Electricity consumption.
  /// @param water Water consumption.
  /// @param symbol Symbol representing the entity.
  /// @param radius Radius of the entity's effect.
  /// @param localEffect Local effect strength.
  /// @param globalEffect Global effect strength.
  /// @param width Width of the entity.
  /// @param height Height of the entity.
  /// @param revenue Revenue generated by the entity.
  /// @param buildTime Time required to build the entity.
  /// @param entityType Type of the entity.
  /// @param size Size category of the entity.
  EntityConfig(const Cost &cost, int electricity, int water, const std::string &symbol,
               int radius, int localEffect, int globalEffect, int width, int height,
               int revenue, int buildTime, EntityType entityType, Size size)
      : cost(cost), electricityConsumption(electricity), waterConsumption(water), symbol(symbol),
        effectRadius(radius), localEffectStrength(localEffect), globalEffectStrength(globalEffect),
        width(width), height(height), revenue(revenue), buildTime(buildTime),
        entityType(entityType), size(size) {}
};

#endif // ENTITYCONFIG_H
