name: CI

on:
  push:
    branches: [main, dev, feature/*, hotfix/*]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ compiler
        uses: llvm/llvm-project@v13

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ curl
          [ ! -f tests/doctest.h ] && curl -sSL https://raw.githubusercontent.com/doctest/doctest/master/doctest/doctest.h -o tests/doctest.h

      - name: Run setup
        run: make setup

      - name: Build project
        run: make

      - name: Run tests
        run: make test

      - name: Run coverage
        run: |
          make coverage
          ls coverage/index.html && echo "Coverage report generated successfully" || echo "Coverage generation failed"

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/index.html
